-- Database: bankdb

DROP DATABASE IF EXISTS bankdb;

CREATE DATABASE bankdb
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- connect to the newly created database
\c bankdb

CREATE TYPE Account_Types AS ENUM (
  'Ahorro',
  'Corriente'
);

CREATE TYPE Movement_Types AS ENUM (
  'Retiro',
  'Deposito'
);

CREATE TABLE Clients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  gender varchar(10) NOT NULL,
  birthdate date NOT NULL,
  person_id varchar UNIQUE NOT NULL,
  address varchar NOT NULL,
  phone varchar(25) NOT NULL,
  password varchar NOT NULL,
  state boolean DEFAULT TRUE
);

CREATE TABLE Accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number varchar UNIQUE NOT NULL,
  type varchar NOT NULL,
  init_balance numeric(14, 2),
  state boolean DEFAULT TRUE,
  client_id int NOT NULL
);

CREATE TABLE Movements (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date timestamp DEFAULT now(),
  type varchar NOT NULL,
  value numeric(14, 2),
  balance numeric(14, 2),
  account_id int NOT NULL
);

CREATE INDEX account_number ON Accounts (number);

ALTER TABLE Accounts ADD FOREIGN KEY (client_id) REFERENCES Clients (id);

ALTER TABLE Movements ADD FOREIGN KEY (account_id) REFERENCES Accounts (id);
